name: CI

on:
  push:
    branches: 
    - main
    - test-ci

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Build project
      uses: nicledomaS/cmake_build_action@v1.4
      with:
        submodule_update: ON
        run_tests: ON
        unit_test_build: -Dtest=ON

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libomp-dev
        sudo apt-get install -y libopencv-dev

    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build
      run: cmake --build build

    - name: Run example tests
      if: env.BUILD_EXAMPLE == 'ON'
      run: build/example

    - name: Run benchmark tests
      if: env.BUILD_BENCHMARK == 'ON'
      run: build/benchmark

    - name: Run example-opencv tests
      if: env.BUILD_EXAMPLE_OPENCV == 'ON'
      run: build/example-opencv
