name: CI

on:
  push:
    branches: 
    - main
    - test-ci

jobs:
  build-linux-x64:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y cmake

    - name: CMake Configure & Generate
      run: cmake -S . -B build -DCMAKE_CXX_FLAGS="-static-libgcc -static-libstdc++" -DBUILD_EXAMPLE:BOOL="1" -DBUILD_EXAMPLE_OPENCV:BOOL="0" -DBUILD_BENCHMARK:BOOL="1" -DBUILD_CUDA_BENCHMARK:BOOL="1" -DBUILD_ROCM_BENCHMARK:BOOL="1" -DUSE_OPENMP:BOOL="0" 

    - name: Build
      run: cmake --build build --config Release

    - name: Run example tests
      run: build/example

    - name: Run benchmark tests
      run: build/benchmark

    - name: Run cuda benchmark tests
      run: build/cuda_benchmark

    - name: Run rocm benchmark tests
      run: build/rocm_benchmark


  build-macos-x64:
    runs-on: macos-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        brew update
        brew install cmake

    - name: CMake Configure & Generate
      run: cmake -S . -B build -DBUILD_EXAMPLE:BOOL="1" -DBUILD_EXAMPLE_OPENCV:BOOL="0" -DBUILD_BENCHMARK:BOOL="1" -DBUILD_CUDA_BENCHMARK:BOOL="0" -DBUILD_ROCM_BENCHMARK:BOOL="0" -DUSE_OPENMP:BOOL="0"

    - name: Build
      run: cmake --build build --config Release

    - name: Run example tests
      run: build/example

    - name: Run benchmark tests
      run: build/benchmark

  build-macos-arm64:
    runs-on: macos-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        brew update
        brew install cmake

    - name: CMake Configure & Generate (ARM64)
      run: cmake -S . -B build-arm -DCMAKE_SYSTEM_PROCESSOR=arm64 -DBUILD_EXAMPLE:BOOL="1" -DBUILD_EXAMPLE_OPENCV:BOOL="0" -DBUILD_BENCHMARK:BOOL="1" -DBUILD_CUDA_BENCHMARK:BOOL="0" -DBUILD_ROCM_BENCHMARK:BOOL="0" -DUSE_OPENMP:BOOL="0"

    - name: Build (ARM)
      run: cmake --build build-arm --config Release

    - name: Run example tests
      run: build-arm/example

    - name: Run benchmark tests
      run: build-arm/benchmark

  build-windows-x64:
    runs-on: windows-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Setup MSVC Developer Command Prompt
      uses: TheMrMilchmann/setup-msvc-dev@v3.0.1
      with: 
        arch: x64
  
    - name: Install dependencies
      run: |
        choco install cmake --force
        #choco install opencv --version=4.10.0 --force

    - name: CMake Configure & Generate
      run: cmake -S . -B build -DBUILD_EXAMPLE:BOOL="1" -DBUILD_EXAMPLE_OPENCV:BOOL="0" -DBUILD_BENCHMARK:BOOL="1" -DBUILD_CUDA_BENCHMARK:BOOL="1" -DBUILD_ROCM_BENCHMARK:BOOL="1" -DUSE_OPENMP:BOOL="0" -DOpenCV_DIR:PATH="C:\tools\opencv\build"

    - name: Build
      run: cmake --build build --config Release

    - name: Run example tests
      run: build\Release\example.exe

    - name: Run benchmark tests
      run: build\Release\benchmark.exe

    - name: Run cuda benchmark tests
      run: build\Release\cuda_benchmark.exe

    - name: Run rocm benchmark tests
      run: build\Release\rocm_benchmark.exe

    # - name: Run example-opencv tests


  build-windows-x86:
    runs-on: windows-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Setup MSVC Developer Command Prompt
      uses: TheMrMilchmann/setup-msvc-dev@v3.0.1
      with: 
        arch: amd64_x86

    - name: Install dependencies
      run: |
        choco install cmake --force

    - name: CMake Configure & Generate
      run: cmake -S . -B build -DBUILD_EXAMPLE:BOOL="1" -DBUILD_BENCHMARK:BOOL="1" -DBUILD_CUDA_BENCHMARK:BOOL="1" -DBUILD_ROCM_BENCHMARK:BOOL="1" -DUSE_OPENMP:BOOL="0" -A Win32

    - name: Build
      run: cmake --build build --config Release

    - name: Run example tests
      run: build\Release\example.exe

    - name: Run benchmark tests
      run: build\Release\benchmark.exe

    - name: Run cuda benchmark tests
      run: build\Release\cuda_benchmark.exe

    - name: Run rocm benchmark tests
      run: build\Release\rocm_benchmark.exe


  build-windows-arm64:
    runs-on: windows-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Setup MSVC Developer Command Prompt
      uses: TheMrMilchmann/setup-msvc-dev@v3.0.1
      with: 
        arch: amd64_arm64

    - name: Install dependencies
      run: |
        choco install cmake --force

    - name: CMake Configure & Generate
      run: cmake -S . -B build -DBUILD_EXAMPLE:BOOL="1" -DBUILD_BENCHMARK:BOOL="1" -DBUILD_CUDA_BENCHMARK:BOOL="1" -DBUILD_ROCM_BENCHMARK:BOOL="1" -DUSE_OPENMP:BOOL="0" -A ARM64

    - name: Build
      run: cmake --build build --config Release

